spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/orders_management
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true    # структуру обслуживает Spring
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true         # включаем во время отладки
