spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:dbname
    driverClassName: org.h2.Driver
    username: sa
    password:
#    url: jdbc:postgresql://localhost:5432/orders_management
#    username: postgres
#    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true    # структуру обслуживает Spring
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true         # включаем во время отладки
