-- insert into ref_goods (id, goods_name, price) values (1, 'товар 1', 11);
-- insert into ref_goods (id, goods_name, price) values (2, 'товар 2', 1.2);
-- insert into ref_goods (id, goods_name, price) values (3, 'товар 3', 1.3);
-- insert into ref_goods (id, goods_name, price) values (4, 'товар 4', 4);
--
-- insert into orders(id, num, order_time, customer) values (1, 01, '2020-07-10 21:00:00', 'vasya@mail.ru');
-- insert into orders(id, num, order_time, customer) values (2, 2, '2020-07-10 21:01:00', 'john.doe@mail.com');
--
-- insert into order_item(id, order_id, goods_id, price, g_count, g_sum) values (1, 1, 1, 11, 2, 22);
-- insert into order_item(id, order_id, goods_id, price, g_count, g_sum) values (2, 1, 2, 1.2, 1, 1.2);
-- insert into order_item(id, order_id, goods_id, price, g_count, g_sum) values (3, 1, 3, 1.3, 3, 3.9);
-- insert into order_item(id, order_id, goods_id, price, g_count, g_sum) values (4, 1, 4, 4, 4, 16);
--
-- insert into order_item(id, order_id, goods_id, price, g_count, g_sum) values (5, 2, 4, 100, 4, 400);
